--USING * TO SELECT ALL AND CONDITION TO ATTACH RELATIONS
SELECT * FROM L_EMP,L_DEPT WHERE L_EMP.deptId = L_DEPT.deptId;

--USING APPROACH 2 WITH SUBQUERY
SELECT empname FROM L_EMP WHERE deptId = (SELECT deptId FROM L_DEPT WHERE deptname = 'Testing');

--USING NOT IN, IN A SUBQUERY
SELECT deptname FROM L_DEPT WHERE deptId NOT IN (SELECT deptId FROM L_EMP);
